export const color1 = "amber-100" // #FCECC9  // beige-y
export const color2 = "amber-400" // #FFC502  // yellow
export const color3 = "orange-600" // #EA6701 // orange
export const color4 = "red-700" // #B1000D    // red
export const color5 = "gray-900" // #090C02   // black

export const codingSkills = [
  {
    id: 1,
    name: "VSCode",
    src: "/assets/skills/--coding/vscode.png",
    title: "VSCode",
    url: "https://code.visualstudio.com/",
  },
  {
    id: 2,
    name: "html5",
    src: "/assets/skills/--coding/html5.png",
    title: "HTML5",
    url: "",
  },
  {
    id: 3,
    name: "css3",
    src: "/assets/skills/--coding/css3.png",
    title: "CSS3",
    url: "",
  },
  {
    id: 4,
    name: "tailwindcss",
    src: "/assets/skills/--coding/tailwindcss.png",
    title: "TailwindCSS",
    url: "https://tailwindcss.com/",
  },
  {
    id: 5,
    name: "javascript",
    src: "/assets/skills/--coding/JavaScript.png",
    title: "JavaScript",
    url: "https://www.javascript.com/",
  },
  {
    id: 6,
    name: "react",
    src: "/assets/skills/--coding/reactjs.png",
    title: "ReactJS",
    url: "https://react.dev/",
  },
  {
    id: 7,
    name: "c#",
    src: "/assets/skills/--coding/csharp.png",
    title: "C#",
    url: "https://dotnet.microsoft.com/en-us/languages/csharp",
  },
  {
    id: 8,
    name: ".NET",
    src: "/assets/skills/--coding/net.png",
    title: ".NET",
    url: "https://learn.microsoft.com/en-us/dotnet/",
  },
  {
    id: 9,
    name: "python",
    src: "/assets/skills/--coding/python.png",
    title: "Python",
    url: "https://www.python.org/doc/",
  },
  {
    id: 10,
    name: "django",
    src: "/assets/skills/--coding/django.png",
    title: "Django",
    url: "https://docs.djangoproject.com/en/5.1/",
  },
  {
    id: 11,
    name: "sql",
    src: "/assets/skills/--coding/sql.png",
    title: "SQL",
    url: "https://learn.microsoft.com/en-us/sql/?view=sql-server-ver16",
  },
  {
    id: 12,
    name: "postgresql",
    src: "/assets/skills/--coding/postgresql.png",
    title: "PostgreSQL",
    url: "https://www.postgresql.org/docs/",
  },
  {
    id: 13,
    name: "sqlite",
    src: "/assets/skills/--coding/sqlite.png",
    title: "SQLite",
    url: "https://www.sqlite.org/docs.html",
  },
  {
    id: 14,
    name: "postman",
    src: "/assets/skills/--coding/postman.png",
    title: "Postman",
    url: "https://www.postman.com/",
  },
  {
    id: 15,
    name: "git",
    src: "/assets/skills/--coding/git.png",
    title: "Git",
    url: "https://git-scm.com/doc",
  },
  {
    id: 16,
    name: "github",
    src: "/assets/skills/--coding/github.png",
    title: "Github",
    url: "https://github.com/",
  },
  {
    id: 17,
    name: "asp.net core",
    src: "/assets/skills/--coding/aspnetcore.png",
    title: "ASP.NET Core",
    url: "https://learn.microsoft.com/en-us/aspnet/core/?view=aspnetcore-8.0",
  },
  {
    id: 18,
    name: "Adobe Photoshop",
    src: "/assets/skills/--computer/adobe_photoshop.png",
    title: "Adobe PhotoShop",
    url: "",
  },
  {
    id: 19,
    name: "Adobe Premier Pro",
    src: "/assets/skills/--computer/adobe_premier_pro.png",
    title: "Adobe Premier Pro",
    url: "",
  },
  {
    id: 20,
    name: "Adobe Media Encoder",
    src: "/assets/skills/--computer/adobe_media_encoder.png",
    title: "Adobe Media Encoder",
    url: "",
  },
  {
    id: 21,
    name: "Companion",
    src: "/assets/skills/--computer/companion.png",
    title: "Companion",
    url: "https://bitfocus.io/companion",
  },
  {
    id: 22,
    name: "BetterTouchTool",
    src: "/assets/skills/--computer/bettertouchtool.png",
    title: "BetterTouchTool",
    url: "https://folivora.ai/",
  },
  {
    id: 23,
    name: "Quicksilver",
    src: "/assets/skills/--computer/quicksilver.png",
    title: "Quicksilver",
    url: "https://qsapp.com/",
  },
]

export const otherSkills = [
  {
    id: 1,
    name: "Ross",
    src: "/assets/skills/--other/ross.png",
    title: "Ross Video",
    url: "https://www.rossvideo.com/",
  },
  {
    id: 2,
    name: "Watchout",
    src: "/assets/skills/--other/watchout.png",
    title: "Dataton Watchout",
    url: "https://www.dataton.com/",
  },
  {
    id: 3,
    name: "BlackMagic Design",
    src: "/assets/skills/--other/blackmagicdesign.webp",
    title: "BlackMagic Design",
    url: "https://www.blackmagicdesign.com/",
  },
  {
    id: 4,
    name: "PlayBack Pro",
    src: "/assets/skills/--other/playbackpro.png",
    title: "DT VideoLabs PlayBack Pro",
    url: "https://www.dtvideolabs.com/dt-videolabs-playbackpro-professional-video-playback/",
  },
  {
    id: 5,
    name: "Mitti",
    src: "/assets/skills/--other/mitti.png",
    title: "Imimot Mitti",
    url: "https://imimot.com/mitti/",
  },
  {
    id: 6,
    name: "Lightware",
    src: "/assets/skills/--other/lightware.jpg",
    title: "Lightware Visual Engineering",
    url: "https://lightware.com/",
  },
  {
    id: 7,
    name: "Barco",
    src: "/assets/skills/--other/barco.png",
    title: "Barco",
    url: "https://www.barco.com/en",
  },
  {
    id: 8,
    name: "Hippotizer",
    src: "/assets/skills/--other/hippotizer.jpg",
    title: "Green Hippo Media Servers",
    url: "https://www.green-hippo.com/hippotizer-media-servers/",
  },
]
